### ISSUE TITLE
Feature Request: Multiple Instance Support

### ISSUE THREAD

**Issue by IstoraMandiri** [0a-/meteor-ace-editor#3]
Looks like right now we can't do multiple instances on one page.

Would be nice to support this, along with the standard ace API, a la http://ace.c9.io/#nav=howto

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Hi Chris, thanks for the suggestions. 

Actually, right now we can have multiple instances. (calling `AceEditor.instance('dom')` does the same thing as `ace.edit('dom')`, it is just that the ace script would only be loaded the first time it is called (so that we don't repeatedly load the same script).)

And everything (stated in the ace API) that can be done with a normal ace instance from `ace.edit(dom)` can be done with an `AceEditor.instance(dom)`. 

My bad for failing to clarify in the readme that this package is actually nothing more than a "wrapper" around the actual ace editor that asynchronously loads the ace editor with XMLHttpRequest when `AceEditor.instance(dom)` is called the first time.

**Comment by IstoraMandiri** [comment]
Okay, great. Thanks for the info. I must admit I was a little confused by:

```
Calling AceEditor.instance() multiple times would not load the Ace script more than one time
```

I am having some issues with calling `AceEditor.instance` more than once within a `rendered` callback -- only the last instance is initialised correctly. However, I will assume it's more to do with ace itself as opposed to this package. Either way I'll let you know if I find any problems.

Thanks for clarifying!
