### ISSUE TITLE
"Unexpected token <"

### ISSUE THREAD

**Issue by johannbotha** [0a-/meteor-ace-editor#6]
<img width="1440" alt="screen shot 2015-10-02 at 3 54 15 pm" src="https://cloud.githubusercontent.com/assets/9872174/10256290/306f1faa-691e-11e5-9e86-e8a8f615239d.png">
![screen shot 2015-10-02 at 3 54 55 pm](https://cloud.githubusercontent.com/assets/9872174/10256291/32ec4e06-691e-11e5-9b7a-62bec015feaf.png)

I see this show up a few times. I also tried with `->` instead of `=>`. I still get the same error. I also get the same sort of error if I pass in the object as the second arguement... I.e.

```
AceEditor.instance("editor", {theme: "iplastic"}, (editor) ->
      editor.setReadOnly(true)
      console.log('foo')
      Session.set('editMode', false)
    );
```

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
If you read the error logs, you would find out that the syntax error is of the first line of `theme-undefined.js`, `mode-undefined,js` and `theme-iplastic.js` which is likely because they don't exist. It should have nothing to do with the way the syntax you use. [See this [SO post](http://stackoverflow.com/questions/18561556/syntax-error-unexpected-token), or you can just google about it] This is likely a result of the set-up of your server & has nothing to with this package. Thus I am closing this.
